steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',  # Disable build cache
      '-t', 'gcr.io/fluted-citizen-269819/chatbot-frontend:$COMMIT_SHA', # Add specific tag
      '-t', 'gcr.io/fluted-citizen-269819/chatbot-frontend:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/fluted-citizen-269819/chatbot-frontend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'chatbot-frontend'
      - '--image'
      - 'gcr.io/fluted-citizen-269819/chatbot-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY