steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',  # Disable build cache
      '-t', 'gcr.io/fluted-citizen-269819/chatbot-backend:$COMMIT_SHA',  # Add specific tag
      '-t', 'gcr.io/fluted-citizen-269819/chatbot-backend:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/fluted-citizen-269819/chatbot-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'chatbot-backend'
      - '--image'
      - 'gcr.io/fluted-citizen-269819/chatbot-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'
options:
  logging: CLOUD_LOGGING_ONLY